# Vaihtoehtoinen tapa määrittää ympäristömuuttujat Docker-kontille on käyttää docker-compose.yml tiedostoa.
# Ennen kuin voit ajaa tämän tiedoston, sinun täytyy luoda .env tiedosto, joka sisältää kaikki ympäristömuuttujat.
# Sen jälkeen asenna dotenv-cli kirjasto, joka lukee .env tiedoston ja asettaa ympäristömuuttujat. npm install dotenv-cli --save-dev
# Käytä dotenv-komentoa lataamaan ympäristömuuttujat ja rakentamaan Docker-kuva:
# dotenv -e .env docker-compose build
# dotenv -e .env docker-compose up

version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
        SUPABASE_PRIVATE_KEY: ${SUPABASE_PRIVATE_KEY}
        SUPABASE_URL: ${SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        LUNNI_API: ${LUNNI_API}
        LUNNI_SERVICES: ${LUNNI_SERVICES}
        LUNNI_UNITS: ${LUNNI_UNITS}
        NEXT_PUBLIC_LUNNI_API: ${NEXT_PUBLIC_LUNNI_API}
        DATABASE_URL: ${DATABASE_URL}
        SECRET: ${SECRET}
    env_file:
      - .env
    ports:
      - "3000:3000"
